### ISSUE TITLE
postgresql: let the installer use a remote postgresql server

### ISSUE THREAD

**Issue by dzen** [Linaro/pkg-lava-server#5]
Hello,

The current debian package states that the postgresql is installed locally and listen only using the local unix socket.

Is there a way to not let the postinst configure the whole instance ?
Thank you.

**Comment by ghost** [comment]
No. The requirements of the distributed deployment model require a local postgres on the master.

**Comment by dzen** [comment]
Hello @codehelp,

What if I already have a postgresql instance, which is not listening on the local unix socket ?
